fix document building
JCSDA-internal/atlas pull request #10
Opened 2020-04-03 16:03 UTC by aerorahul

Change-Id: I7372755054e3cab2f86943e718f3e592b5f5396b
Use cmake provided FindLATEX.cmake

2020-04-03 16:05 UTC, aerorahul commented
Note that `jcsda::develop`, lags `ecmwf::develop`.
`ecmwf::develop` has changed how it enables/disables features.
Some additional work will be required when `ecmwf::develop` is merged into `jcsda::develop`.

2020-04-06 21:13 UTC, mmiesch commented
Thanks @aerorahul - latex is found for me but the documentation still isn't building.  Still, this is an improvement.

2020-04-06 21:16 UTC, aerorahul commented
> Thanks @aerorahul - latex is found for me but the documentation still isn't building. Still, this is an improvement.

I think the COMPONENTS should be added `PDFLATEX`, `BIBTEX`, `MAKE_INDEX` and `HTLATEX`.
Those are used.
In addition `convert` program from `imagemagick` is used.

With all those found, I could build everything; pdf and html on my mac.

2020-04-07 20:23 UTC, mmiesch commented
Thanks @aerorahul - I installed imagemagick and ford, I have all the other packages you mentioned, they are all found, and I'm building with  ```-DENABLE_DOCS=ON``` but I'm still not seeing anything useful in the atlas/doc directory.  The html directory is empty and there are no pdfs.

2020-04-07 20:26 UTC, aerorahul commented
> Thanks @aerorahul - I installed imagemagick and ford, I have all the other packages you mentioned, they are all found, and I'm building with `-DENABLE_DOCS=ON` but I'm still not seeing anything useful in the atlas/doc directory. The html directory is empty and there are no pdfs.

The docs are not built with just `make -j<threads>`.  That only builds the code.
One has to explicitly do `make atlas_doc` or `make atlas_html` for the docs to be created.
Also, you cannot use make -j<threads> for creating docs.

2020-04-07 20:27 UTC, aerorahul commented
> > Thanks @aerorahul - I installed imagemagick and ford, I have all the other packages you mentioned, they are all found, and I'm building with `-DENABLE_DOCS=ON` but I'm still not seeing anything useful in the atlas/doc directory. The html directory is empty and there are no pdfs.
> 
> The docs are not built with just `make -j<threads>`. That only builds the code.
> One has to explicitly do `make atlas_doc` or `make atlas_html` for the docs to be created.
> Also, you cannot use make -j for creating docs.

type `make help` in the  `atlas` directory`.  There are other ones too. see below.
```
... doc
... atlas_doc
... atlas_doc_html
... atlas_doc_pdf
... atlas_doc_code
... atlas-user-guide-pdf
... atlas-user-guide-html
```

2020-04-07 20:33 UTC, mmiesch commented
Thanks but I'm still having problems - have you ever seen this?
~~~~~
miesch:~/JEDI/code/working_copy/build/atlas/doc/user-guide$ make atlas-user-guide-pdf
make[3]: *** [atlas/doc/user-guide/CMakeFiles/atlas-user-guide-pdf] Error 1
make[2]: *** [atlas/doc/user-guide/CMakeFiles/atlas-user-guide-pdf.dir/all] Error 2
make[1]: *** [atlas/doc/user-guide/CMakeFiles/atlas-user-guide-pdf.dir/rule] Error 2
make: *** [atlas/doc/user-guide/CMakeFiles/atlas-user-guide-pdf.dir/rule] Error 2
~~~~~

2020-04-07 20:36 UTC, aerorahul commented
can you go to the top of the build directory and do the same command?
```
cd ~/JEDI/code/working_copy/build/atlas
make atlas-user-guide-pdf
```

2020-04-07 20:41 UTC, mmiesch commented
There I get:
~~~~~
miesch:~/JEDI/code/working_copy/build/atlas$ make atlas-user-guide-pdf
make: *** No rule to make target `atlas-user-guide-pdf'.  Stop.
~~~~~
VERBOSE isn't much help.  Did you add any other options to ecbuild?

2020-04-07 20:47 UTC, aerorahul commented
> There I get:
> 
> ```
> miesch:~/JEDI/code/working_copy/build/atlas$ make atlas-user-guide-pdf
> make: *** No rule to make target `atlas-user-guide-pdf'.  Stop.
> ```
> 
> VERBOSE isn't much help. Did you add any other options to ecbuild?

Make sure that you are actually running make at the top of the atlas build directory.
Is build your top level directory where you did ecbuild /path/to/atlas/clone?

Then there is where you should do make atlas-user-guide-pdf

do a make help at that level too

2020-04-07 20:54 UTC, mmiesch commented
It is more informative if I build atlas on it's own - then I do see all the options at the top level - it looks like some cmake variable is empty:
~~~~~
$make VERBOSE=1  atlas-user-guide-pdf
[...]
cd /Users/miesch/JEDI/code/working_copy/src/ufo-bundle/atlas/doc/user-guide && export TEXINPUTS=/Users/miesch/JEDI/code/working_copy/src/ufo-bundle/atlas//:/Users/miesch/JEDI/code/working_copy/build-atlas/doc/user-guide//: && --output-directory /Users/miesch/JEDI/code/working_copy/build-atlas/doc/user-guide /Users/miesch/JEDI/code/working_copy/src/ufo-bundle/atlas/doc/user-guide/user-guide.tex
/bin/sh: --output-directory: command not found
~~~~~

2020-04-07 20:58 UTC, mmiesch commented
Yeah - it looks like PDFLATEX is not being set - I'll poke around a bit more.  Thanks for the help
~~~~
./user-guide/CMakeLists.txt:   ${PDFLATEX} --output-directory ${USERGUIDE} ${USERGUIDESRC}/user-guide.tex
~~~~~

2020-04-07 21:01 UTC, aerorahul commented
> It is more informative if I build atlas on it's own - then I do see all the options at the top level - it looks like some cmake variable is empty:
> 
> ```
> $make VERBOSE=1  atlas-user-guide-pdf
> [...]
> cd /Users/miesch/JEDI/code/working_copy/src/ufo-bundle/atlas/doc/user-guide && export TEXINPUTS=/Users/miesch/JEDI/code/working_copy/src/ufo-bundle/atlas//:/Users/miesch/JEDI/code/working_copy/build-atlas/doc/user-guide//: && --output-directory /Users/miesch/JEDI/code/working_copy/build-atlas/doc/user-guide /Users/miesch/JEDI/code/working_copy/src/ufo-bundle/atlas/doc/user-guide/user-guide.tex
> /bin/sh: --output-directory: command not found
> ```

I did a clean clone and build
I have eckit and fckit already built and available as modules

```
git clone -b bugfix/docs github:jcsda/atlas
cd atlas
mkdir -p build; cd build
ecbuild -DENABLE_DOCS=ON ..
make -j4
make doc
ls doc/user-guide
CMakeFiles           core-functionalities user-guide.idx       user-guide.toc
CTestTestfile.cmake  getting-started      user-guide.log       version.tex
Makefile             html                 user-guide.out
cmake_install.cmake  user-guide.aux       user-guide.pdf

```

2020-04-07 21:17 UTC, mmiesch commented
Ok - I found it - it looks like the old ```FindLatex``` in the develop branch (which works for me) defined a ```PDFLATEX``` variable that my cmake 3.17 ```FindLATEX``` does not.  Instead, it defines ```PDFLATEX_COMPILER```.  So, with this substitution the atlas-user-guide-pdf target works for me.  I suspect similar replacements will be needed for the other components

2020-04-07 22:01 UTC, aerorahul commented
> Yeah - it looks like PDFLATEX is not being set - I'll poke around a bit more. Thanks for the help
> 
> ```
> ./user-guide/CMakeLists.txt:   ${PDFLATEX} --output-directory ${USERGUIDE} ${USERGUIDESRC}/user-guide.tex
> ```



> Ok - I found it - it looks like the old `FindLatex` in the develop branch (which works for me) defined a `PDFLATEX` variable that my cmake 3.17 `FindLATEX` does not. Instead, it defines `PDFLATEX_COMPILER`. So, with this substitution the atlas-user-guide-pdf target works for me. I suspect similar replacements will be needed for the other components

FindLATEX.cmake finds `PDFLATEX` and other components.  We should not be using `PDFLATEX_COMPILER`. 
This implies your latex installation is not correct.
See [here](https://cmake.org/cmake/help/v3.17/module/FindLATEX.html) for what is expected to be found from `FindLATEX.cmake`

2020-04-07 22:22 UTC, aerorahul commented on doc/user-guide/CMakeLists.txt
> +   ${PDFLATEX_COMPILER} --output-directory ${USERGUIDE} ${USERGUIDESRC}/user-guide.tex
This is not a legitimate return of FindLATEX.cmake.
The FindLATEX.cmake returns PDFLATEX.
Please revert this change.

2020-04-07 22:25 UTC, mmiesch commented
The package name isn't always the same as the executable, is it?  The way atlas is using it is as an executable program contained in a variable.  Isn't that what ```PDFLATEX_COMPILER``` is?  I'm not replacing the ```find_package``` command - just where the executable is called.  If you look at the FindLATEX, it's using find_program to define ```PDFLATEX_COMPILER```
~~~~~
miesch:/usr/local/share/cmake/Modules$ grep PDFLATEX FindLATEX.cmake 
  PDFLATEX_COMPILER:    path to the PdfLaTeX compiler
  PDFLATEX
  find_package(LATEX COMPONENTS PDFLATEX)
find_program(PDFLATEX_COMPILER
if (PDFLATEX_COMPILER)
  set(LATEX_PDFLATEX_FOUND TRUE)
  set(LATEX_PDFLATEX_FOUND FALSE)
  PDFLATEX_COMPILER
~~~~~

2020-04-07 22:26 UTC, aerorahul commented
> The package name isn't always the same as the executable, is it? The way atlas is using it is as an executable program contained in a variable. Isn't that what `PDFLATEX_COMPILER` is? I'm not replacing the `find_package` command - just where the executable is called. If you look at the FindLATEX, it's using find_program to define `PDFLATEX_COMPILER`
> 
> ```
> miesch:/usr/local/share/cmake/Modules$ grep PDFLATEX FindLATEX.cmake 
>   PDFLATEX_COMPILER:    path to the PdfLaTeX compiler
>   PDFLATEX
>   find_package(LATEX COMPONENTS PDFLATEX)
> find_program(PDFLATEX_COMPILER
> if (PDFLATEX_COMPILER)
>   set(LATEX_PDFLATEX_FOUND TRUE)
>   set(LATEX_PDFLATEX_FOUND FALSE)
>   PDFLATEX_COMPILER
> ```

You are right.  Similar edits will be necessary for the other components I think.

2020-04-07 22:31 UTC, mmiesch commented
Good, I'm glad you agree - it seems to work.  I think the only other thing that needs to be changed is a call to HTLATEX.  While testing I ran into a bug in my latex so I'm installing mactex now - taking forever.  I'll push the change soon.

2020-04-07 22:40 UTC, aerorahul commented
> Good, I'm glad you agree - it seems to work. I think the only other thing that needs to be changed is a call to HTLATEX. While testing I ran into a bug in my latex so I'm installing mactex now - taking forever. I'll push the change soon.

I brew-ed mactex.

2020-04-07 23:01 UTC, mmiesch commented
Ok, all the various pdf, html, and code doc build targets are working for me now.  Thanks @aerorahul for your help

2020-04-07 23:02 UTC, mmiesch approved these changes

2020-04-07 23:12 UTC, ytremolet requested changes
We should issue PRs into ECMWF's develop, not JCSDA's.

2020-04-08 13:30 UTC, aerorahul commented
@mmiesch @ytremolet 
Is it permitted to sync `jcsda::atlas/develop` with `ecmwf::atlas/develop`?
If that is done, this branch is redundant and PR can be issued to ECMWF

2020-04-08 14:15 UTC, aerorahul commented
I opened a PR on the ECMWF::atlas/develop [here](https://github.com/ecmwf/atlas/pull/18). I cannot add reviewers, so I mentioned @ytremolet in the PR.

2020-04-08 14:38 UTC, mmiesch commented
Thanks @aerorahul

2020-04-08 16:29 UTC, ytremolet commented
We should bring our develop to be up to date with ecmwf's. In fact I would really like if we could make that automatic so it's always up to date.

2020-04-14 15:21 UTC, aerorahul commented
@mmiesch @ytremolet 
I am closing this PR.
A PR on ECMWF::atlas/develop [here](https://github.com/ecmwf/atlas/pull/18) was accepted and closed.  We should sync up with ECMWF.

2020-04-14 15:22 UTC, closed without merging