Atlas OpenMP dependency propogation and fixes
JCSDA-internal/atlas pull request #9
Opened 2020-03-03 01:23 UTC by markjolah

* Atlas uses OpenMP directives in it's provided .h files.  Therefore OpenMP is a PUBLIC link dependency.
* Find gridtools quietly
* Fix problematic quote escapes
* Allow overcommit for testing when using srun on systems with SLURM installed.

Will also need `fv3-jedi/feature/openmp_headers` branch if building fv3-bundle with this PR.

2020-03-03 12:38 UTC, ytremolet requested changes
@markjolah Can you split this from the code that was put in by @benjaminmenetrier and issue a PR on the ECMWF repo? Thanks.

2020-03-03 17:22 UTC, markjolah commented
@ytremolet The ecmwf/develop branch has a completely different build system from what our branch is.  How far out of date are we?  I guess I need this PR to go in for this fork of Atlas.  I'm not sure if I can submit an upstream PR as it will be completely different, and I can't really test it.   We should maybe prioritize getting up-to-date with the current ecmwf/develop.

2020-03-04 09:28 UTC, danholdaway commented
@markjolah there's a branch feature/dev-ec that we were testing to be merged into our develop. But one of the tests triggered a bug in atlas that needs to be fixed. Could branch off of that and add your changes?

2020-03-04 10:53 UTC, ytremolet commented
We can merge this PR, that's ok. But we should also issue the same PR to ecmwf.

2020-03-04 14:10 UTC, ytremolet reviewed
FYI: I am able to run with the branch develop-jcsda on the ecmwf repo even though it has all the ecmwf changes.

2020-03-04 17:14 UTC, markjolah commented
OK.  I will investigate and make a seperate PR.  I'm guessing you all are in the middle of updating ecmwf/develop so I shouldn't expect that to work with JEDI presently?

2020-04-23 21:26 UTC, mmiesch commented
JCSDA develop is now in synch with ecmwf develop.  I'd like to close this PR and resubmit it upstream.  @markjolah - it is ready to be submitted upstream?

2020-04-28 15:49 UTC, markjolah commented
Will close this for now, as it may be fixed in the new develop.  If it comes up again I will reopen.

2020-04-28 15:50 UTC, closed without merging